apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
  namespace: service-registry
spec:
  selector:
    matchLabels:
      app: eureka
  serviceName: "eureka"
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: saitej150/serviceregistry:0.0.1
        ports:
        - containerPort: 8761

---

apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: service-registry
spec:
  clusterIP: None
  selector:
    app: eureka
  ports:
  - port: 8761
    name: eureka

---

apiVersion: v1
kind: Service
metadata:
  name: eureka-lb
  namespace: service-registry  # This is for argo cd namespace to deploy
spec:
  type: NodePort
  selector:
    app: eureka
  ports:
  - port: 80
    targetPort: 8761


