apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-registry
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/saitej07/ServiceRegistry.git'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: service-registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true